apiVersion: v2
name: du
description: Accelleran 5G DU Components
type: application
version: 0.0.4
# renovate: image=accelleran/du
appVersion: "4.3.1"
dependencies:
  - name: common
    version: 0.5.0
    repository: https://accelleran.github.io/helm-charts/
